remove:
	rm -rf Resultados log.txt Resultado.csv saida.json

diffprisao1:
	diff Casos/1/saida/saida.txt Resultados/Pedro/prisao/Casos/1/saida/saida.txt

diffprisao2:
	diff Casos/2/saida/saida.txt Resultados/Pedro/prisao/Casos/2/saida/saida.txt

diffprisao3:
	diff Casos/3/saida/saida.txt Resultados/Pedro/prisao/Casos/3/saida/saida.txt